<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [1]:
#Импорт библиотек
import pandas as pd
import psycopg2
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Подкючение к серверу
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [4]:
# Считаем общее количество вакансий
query_3_1 = f'''select count(*)
           from public.vacancies  
        '''

In [5]:
# результат запроса
df_3_1 = pd.read_sql_query(query_3_1, connection)
display(f'Количество вакансий в базе {int(df_3_1['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1008997593.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_1 = pd.read_sql_query(query_3_1, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1008997593.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество вакансий в базе {int(df_3_1['count'])}')

'Количество вакансий в базе 49197'

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [6]:
# Считаем общее количество работодателей
query_3_2 = f'''select count(*)
           from public.employers 
        '''

In [7]:
# результат запроса
df_3_2 = pd.read_sql_query(query_3_2, connection)
display(f'Количество работодателей в базе {int(df_3_2['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\4184302181.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_2 = pd.read_sql_query(query_3_2, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\4184302181.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество работодателей в базе {int(df_3_2['count'])}')

'Количество работодателей в базе 23501'

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [ ]:
# Считаем общее количество регионов
query_3_3 = f'''select count(name)
           from public.areas 
        '''

In [9]:
# результат запроса 
df_3_3 = pd.read_sql_query(query_3_3, connection)
display(f'Количетсво регионов в базе {int(df_3_3['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2274468093.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_3 = pd.read_sql_query(query_3_3, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2274468093.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количетсво регионов в базе {int(df_3_3['count'])}')

'Количетсво регионов в базе 1362'

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [55]:
#Считаем общее количество сфер деятельности 
query_3_4 = f'''select count(name)
            from public.industries 
        '''

In [56]:
# результат запроса df = pd.read_sql_query(query_3_1, connection)
df_3_4 = pd.read_sql_query(query_3_4, connection)
display(f'Количетсво сфер деятельности в базе {int(df_3_4['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3247703840.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_4 = pd.read_sql_query(query_3_4, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3247703840.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количетсво сфер деятельности в базе {int(df_3_4['count'])}')

'Количетсво сфер деятельности в базе 294'

***

<strong>Исходя из предварительного анализа данных можно увидеть, что объём данных достаточно большой, почти 50.000 вакансий, в более, чем 1.300 регионов по всему миру, от больше, чем 23.000 работадателей, в почти 300 различных сферах деятельности. На основании этих выводов можно утверждать, что для наиболее точного подбора вакансии, нужно немало условий, необходимых для искателя вакансии.
</strong>

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [12]:
# текст запроса
query_4_1 = f'''select a.name, count(v.id)
from public.vacancies v 
join public.areas a on v.area_id = a.id 
group by a.name
order by 2 desc
'''

In [13]:
# результат запроса
df_4_1 = pd.read_sql_query(query_4_1, connection)
display('Количество вакансий в каждом регионе')
df_4_1

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3769415204.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_1 = pd.read_sql_query(query_4_1, connection)

'Количество вакансий в каждом регионе'

                name  count
0             Москва   5333
1    Санкт-Петербург   2851
2              Минск   2112
3        Новосибирск   2006
4             Алматы   1892
..               ...    ...
764       Тарко-Сале      1
765    Новоаннинский      1
766            Бирск      1
767           Сасово      1
768             Анна      1

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [14]:
# текст запроса
query_4_2 = f'''select count(id)
from public.vacancies v
where v.salary_from is not null or v.salary_to is not null
'''

In [15]:
# результат запроса
df_4_2 = pd.read_sql_query(query_4_2, connection)
display(f'У {int(df_4_2['count'])} вакансий заполнены хотя бы одно поле с желаемой зарплатой')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3715717719.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_2 = pd.read_sql_query(query_4_2, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3715717719.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'У {int(df_4_2['count'])} вакансий заполнены хотя бы одно поле с желаемой зарплатой')

'У 24073 вакансий заполнены хотя бы одно поле с желаемой зарплатой'

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [16]:
# текст запроса
query_4_3 = f'''select round(avg(salary_from)) low_bound_avg, round(avg(salary_to)) upper_bound_avg
from public.vacancies v'''

In [17]:
# результат запроса
df_4_3 = pd.read_sql_query(query_4_3, connection)
display(f'Среднее значение для нижней границы: {int(df_4_3['low_bound_avg'])}, для верхней: {int(df_4_3['upper_bound_avg'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1608250641.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_3 = pd.read_sql_query(query_4_3, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1608250641.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Среднее значение для нижней границы: {int(df_4_3['low_bound_avg'])}, для верхней: {int(df_4_3['upper_bound_avg'])}')

'Среднее значение для нижней границы: 71065, для верхней: 110537'

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [18]:
# текст запроса
query_4_4 = f'''select schedule,employment,count(id) 
from public.vacancies v
group by schedule, employment
order by 3 desc'''

In [19]:
# результат запроса
df_4_4 = pd.read_sql_query(query_4_4, connection)
display('Количество вакансий для каждого сочетания типа трудоустройства и рабочего графика')
df_4_4

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1978001784.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_4 = pd.read_sql_query(query_4_4, connection)

'Количество вакансий для каждого сочетания типа трудоустройства и рабочего графика'

            schedule           employment  count
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [20]:
# текст запроса
query_4_5 = f'''select experience, count(id)
from public.vacancies v
group by experience
order by 2
'''

In [21]:
# результат запроса
df_4_5 = pd.read_sql_query(query_4_5, connection)
display('Количество вакансий для каждой категории требуемого опыта')
df_4_5

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\733361665.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_4_5 = pd.read_sql_query(query_4_5, connection)

'Количество вакансий для каждой категории требуемого опыта'

           experience  count
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

<strong>Исходя из более детального анализа предоставленных данных, видно, что большинство вакансий требуют опыт от 1 года до 6 лет, с полной занятостью на полный день, при этом больше половины вакансий не указывают нижнюю и верхнюю границы заработной платы, а также, большая часть вакансий в крупных городах.
</strong>

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [22]:
# текст запроса
query_5_1 = f'''(select e.name, count(v.id)
from public.employers e
join public.vacancies v on e.id= v.employer_id
group by e.name
order by 2 desc
limit 1) 
union all
(select e.name, count(v.id)
from public.employers e
join public.vacancies v on e.id= v.employer_id
group by e.name
order by 2 desc
limit 1 offset 4)
'''

In [23]:
# результат запроса
df_5_1 = pd.read_sql_query(query_5_1, connection)
display(f'На первом месте по количеству вакансий находится компания: {df_5_1['name'].iloc[0]}, на пятом компания {df_5_1['name'].iloc[1]}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3964700506.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_1 = pd.read_sql_query(query_5_1, connection)

'На первом месте по количеству вакансий находится компания: Яндекс, на пятом компания Газпром нефть'

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [24]:
# текст запроса
query_5_2 = f'''select a.name, count(v.id) cnt_vacancies, count(e.id) cnt_employers
from public.areas a
left join public.vacancies v on a.id = v.area_id
left join public.employers e on a.id = e.area

group by a.name
having count(v.id) = 0 
order by 3 desc
limit 1
'''

In [25]:
# результат запроса
df_5_2 = pd.read_sql_query(query_5_2, connection)
display(f'Регион, в котором нет вакансий, но есть работодатели: {df_5_2['name'].iloc[0]}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\455648719.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_2 = pd.read_sql_query(query_5_2, connection)

'Регион, в котором нет вакансий, но есть работодатели: Россия'

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [26]:
# текст запроса
query_5_3 = f'''SELECT e.name, count(distinct v.area_id)
FROM public.vacancies v
join public.employers e on v.employer_id = e.id
group by e.name
order by 2 desc
'''

In [27]:
# результат запроса
df_5_3 = pd.read_sql_query(query_5_3, connection)
display('Количество регионов для каждого работодателя, в которых он публикует свои вакансии')
df_5_3

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2133156128.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_3 = pd.read_sql_query(query_5_3, connection)

'Количество регионов для каждого работодателя, в которых он публикует свои вакансии'

                         name  count
0                      Яндекс    181
1                  Ростелеком    152
2                  Спецремонт    116
3      Поляков Денис Иванович     88
4                   ООО ЕФИН      71
...                       ...    ...
14761                  UniSol      1
14762            UNISTORY LLC      1
14763                   UNIT6      1
14764     United Distribution      1
14765              UNITEL LLC      1

[14766 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [28]:
# текст запроса
query_5_4 = f'''select count( e.name)
from public.employers e 
left join public.employers_industries ei on e.id = ei.employer_id
where industry_id is null
'''

In [29]:
# результат запроса
df_5_4 = pd.read_sql_query(query_5_4, connection)
display(f'Количество работодателей, у которых не указана сфера деятельности: {int(df_5_4['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1874911585.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_4 = pd.read_sql_query(query_5_4, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\1874911585.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество работодателей, у которых не указана сфера деятельности: {int(df_5_4['count'])}')

'Количество работодателей, у которых не указана сфера деятельности: 8419'

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [30]:
# текст запроса
query_5_5 = f'''select distinct e.name
from public.employers e 
join public.employers_industries ei on e.id = ei.employer_id
group by e.name
having count(ei.industry_id) = 4
order by 1
offset 2 limit 1
'''

In [31]:
# результат запроса
df_5_5 = pd.read_sql_query(query_5_5, connection)
display(f'Компания, на третьем месте в алфавитном списке (по названию) компаний, у которой указано четыре сферы деятельности: {df_5_5['name'].iloc[0]}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\716629012.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_5 = pd.read_sql_query(query_5_5, connection)

'Компания, на третьем месте в алфавитном списке (по названию) компаний, у которой указано четыре сферы деятельности: 2ГИС'

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [32]:
# текст запроса
query_5_6 = f'''select count(ei.employer_id)
from public.employers_industries ei 
join public.industries i on ei.industry_id = i.id
where i.name = 'Разработка программного обеспечения'
'''

In [33]:
# результат запроса
df_5_6 = pd.read_sql_query(query_5_6, connection)
display(f'Количество работодателей,у которых в качестве сферы деятельности указана Разработка программного обеспечения {int(df_5_6['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2394708307.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_6 = pd.read_sql_query(query_5_6, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2394708307.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество работодателей,у которых в качестве сферы деятельности указана Разработка программного обеспечения {int(df_5_6['count'])}')

'Количество работодателей,у которых в качестве сферы деятельности указана Разработка программного обеспечения 3553'

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [34]:
# код для получения списка городов-милионников
import requests
from bs4 import BeautifulSoup
url = 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8'
response = requests.get(url)
page = BeautifulSoup(response.text, 'html.parser')
city = []
for x in page.table.tbody:
    city.append(x.a.text)
city =city[1:]
city = tuple(city)

display(f'Список городов-миллиоников: {city}')

"Список городов-миллиоников: ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа', 'Краснодар', 'Самара', 'Ростов-на-Дону', 'Омск', 'Воронеж', 'Пермь', 'Волгоград')"

In [35]:
# текст запроса
query_5_7 = f'''(select a.name, count(v.id)
from public.employers e
join public.vacancies v on v.employer_id = e.id
join public.areas a on a.id = v.area_id
where e.name = 'Яндекс' and a.name in {city}
group by a.id)
union all
(select 'Total', count(*) cnt
from public.employers e
join public.vacancies v on v.employer_id = e.id
join public.areas a on a.id = v.area_id
where e.name = 'Яндекс' and a.name in {city}
)'''

In [36]:
# результат запроса
df_5_7 = pd.read_sql_query(query_5_7, connection)
display('Общее количество вакансий в городах-миллиониках России и распределение их по каждому из городов')
df_5_7

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\4190784411.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_5_7 = pd.read_sql_query(query_5_7, connection)

'Общее количество вакансий в городах-миллиониках России и распределение их по каждому из городов'

               name  count
0             Total    485
1            Москва     54
2   Санкт-Петербург     42
3      Екатеринбург     39
4       Новосибирск     35
5         Волгоград     24
6           Воронеж     32
7         Краснодар     30
8        Красноярск     23
9   Нижний Новгород     36
10             Омск     21
11            Пермь     25
12   Ростов-на-Дону     25
13           Самара     26
14           Казань     25
15              Уфа     26
16        Челябинск     22

***

<strong>Проанализировав представленных работадателей видно, что большинство вакансий предлагают крупнейшие российские компании из разных сфер деятельности. Рекордсменом среди них является Яндекс, который также публикует вакансии в наибольшем количестве регионов. Также, из важных выводов можно выделить, что практически 8.500 работадателей не указали сферу деятельности.
</strong>

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [37]:
# текст запроса
query_6_1 = f'''select  count(v.id)
from public.vacancies v
where lower(v.name) like '%data%' or lower(v.name) like '%данн%'
'''

In [38]:
# результат запроса
df_6_1 = pd.read_sql_query(query_6_1, connection)
display(f'Количество вакансий имеющих отношение к данным {int(df_6_1['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\745202449.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_1 = pd.read_sql_query(query_6_1, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\745202449.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество вакансий имеющих отношение к данным {int(df_6_1['count'])}')

'Количество вакансий имеющих отношение к данным 1771'

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [39]:
# текст запроса
query_6_2 = f'''select  count(v.name)
from public.vacancies v
where 
(
(v.name ilike '%data scientist%') 
or (v.name ilike '%data science%') 
or (v.name ilike '%исследователь данных%') 
or ((v.name ilike '%ML%') and (v.name not ilike '%HTML%'))
or (v.name ilike '%machine learning%') 
or (v.name ilike '%машинн%обучен%')
and (v.key_skills is not null)
)

and (v.name ilike '%junior%'
or v.experience ilike '%Нет опыта%'
or v.employment ilike '%Стажировка%')

'''

In [40]:
# результат запроса
df_6_2 = pd.read_sql_query(query_6_2, connection)
display(f'Количество вакансий, подходящие для нaчинающего дата-сайентиста {int(df_6_2['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\430423829.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_2 = pd.read_sql_query(query_6_2, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\430423829.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество вакансий, подходящие для нaчинающего дата-сайентиста {int(df_6_2['count'])}')

'Количество вакансий, подходящие для нaчинающего дата-сайентиста 51'

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [41]:
# текст запроса
query_6_3 = f'''select  count(v.name)
from public.vacancies v
where 
(
(v.name ilike '%data scientist%') 
or (v.name ilike '%data science%') 
or (v.name ilike '%исследователь данных%') 
or ((v.name ilike '%ML%') and (v.name not ilike '%HTML%'))
or (v.name ilike '%machine learning%') 
or (v.name ilike '%машинн%обучен%')
and (v.key_skills is not null)
)
and (v.key_skills ilike '%SQL%'
or v.key_skills ilike '%postgres%')
'''

In [42]:
# результат запроса
df_6_3 = pd.read_sql_query(query_6_3, connection)
display(f'Количество вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres: {int(df_6_3['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\236688250.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_3 = pd.read_sql_query(query_6_3, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\236688250.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres: {int(df_6_3['count'])}')

'Количество вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres: 229'

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [43]:
# текст запроса
query_6_4 = f'''select  count(v.name)
from public.vacancies v
where 
(
(v.name ilike '%data scientist%') 
or (v.name ilike '%data science%') 
or (v.name ilike '%исследователь данных%') 
or ((v.name ilike '%ML%') and (v.name not ilike '%HTML%'))
or (v.name ilike '%machine learning%') 
or (v.name ilike '%машинн%обучен%')
and (v.key_skills is not null)
)
and (v.key_skills ilike '%python%')
'''

In [44]:
# результат запроса
df_6_4 = pd.read_sql_query(query_6_4, connection)
display(f'Количество вакансий, в которых в качестве ключевого навыка указан Python {int(df_6_4['count'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2818021432.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_4 = pd.read_sql_query(query_6_4, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2818021432.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display(f'Количество вакансий, в которых в качестве ключевого навыка указан Python {int(df_6_4['count'])}')

'Количество вакансий, в которых в качестве ключевого навыка указан Python 357'

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [45]:
# текст запроса
query_6_5 = f'''select round(avg(LENGTH(key_skills) - LENGTH(replace(key_skills, CHR(9),'')) + 1),2)
from public.vacancies
where 
(
name ilike '%data scientist%' 
or name ilike '%data science%' 
or name ilike '%исследователь данных%'
or (name like '%ML%' and name not like '%HTML%')
or name ilike '%machine learning%' 
or name ilike '%машинн%обучен%'
and key_skills is not null
)


'''

In [46]:
# результат запроса
df_6_5 = pd.read_sql_query(query_6_5, connection)
display(f'Количество ключевых навыков, которые в среднем указывают в вакансиях для DS {float(df_6_5['round'])}')

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\37668979.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_5 = pd.read_sql_query(query_6_5, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\37668979.py:3: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  display(f'Количество ключевых навыков, которые в среднем указывают в вакансиях для DS {float(df_6_5['round'])}')

'Количество ключевых навыков, которые в среднем указывают в вакансиях для DS 6.41'

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [47]:
# текст запроса
query_6_6 = f'''select experience, round(avg(coalesce((salary_from + salary_to) / 2, salary_from, salary_to)),0) as average
from public.vacancies
where 
(
name ilike '%data scientist%' 
or name ilike '%data science%' 
or name ilike '%исследователь данных%'
or (name like '%ML%' and name not like '%HTML%')
or name ilike '%machine learning%' 
or name ilike '%машинн%обучен%'
)
and (salary_from is not null or salary_to is not null)
group by experience
'''

In [48]:
# результат запроса
df_6_6 = pd.read_sql_query(query_6_6, connection)
display('Средняя з/п для data science специалиста с опытом от 3 до 6 лет {}'.format(int(df_6_6[df_6_6['experience'] == 'От 3 до 6 лет']['average'])))

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3495409586.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_6_6 = pd.read_sql_query(query_6_6, connection)
C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\3495409586.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  display('Средняя з/п для data science специалиста с опытом от 3 до 6 лет {}'.format(int(df_6_6[df_6_6['experience'] == 'От 3 до 6 лет']['average'])))

'Средняя з/п для data science специалиста с опытом от 3 до 6 лет 243115'

***

<strong> Исходя из предметного анализа данных, я могу обратить внимание на достаточно скудное количество вакансий для начинающих дата-сайентистов, специалистов, от которых требуется знание SQL и Python и, относительно общего числа вакансий, вакансий для специалистов по данным. Но также отрадно наблюдать и мотивирует предлагаемая заработная плата для дата-сайентистов имеющих опыт от 3-х лет.
</strong>

# Общий вывод по проекту

<strong> Обобщая выводы по проделанным анализам предоставленных данных можно сделать выводы о том, что база имеет большое количество вакансий с предложениями для различных специалистов с разным объемом опыта работы, разным количеством необходимых навыков, большое разнообразие вариантов графика работы, места работы и ,конечно же, размера заработной платы. <br>

На основании этого мы можем утверждать, что на основании этой базы данных мы можем подобрать подходящюю вакансию большому количеству искателей, но необходимо немало параметров для фильтрации и отсева вакансий, для подбора наиболее подходящего и желаемого варианта трудоустройства.<br>

Касаемо вариантов для людей, которые хотят работать в дальнейшем в области Data Science, мы можем увидеть, что вакансий для специалистов совсем без опыта достаточно мало, что ключевых требуемых навыков для таких специалистов в среднем, больше 6, но при приобретении опыта количество вакансий и заработная плата сильно возрастает, что свидетельствует о том, что для развития в этой сфере самое важное это приобретение опыта работы и расширение пула активных навыков.
</strong>

<strong> Для анализа самых востребованных специалистов предлагаю взглянуть на топ-10 количества вакансий для той или иной специальности
</strong>

In [49]:
# подведем итог исследования, обобщите выводы
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования
query_7_3 = f'''select distinct name "Название вакансии", count(*) "Количество вакансий"
from public.vacancies
group by name
order by 2 desc
limit 10
'''

In [50]:
df_7_3 = pd.read_sql_query(query_7_3, connection)
display('Топ-10 самых востребованных специалистов')
df_7_3

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\2516964714.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_7_3 = pd.read_sql_query(query_7_3, connection)

'Топ-10 самых востребованных специалистов'

                  Название вакансии  Количество вакансий
0           Системный администратор                 1761
1                    Программист 1С                 1153
2                   Бизнес-аналитик                  488
3  Специалист технической поддержки                  457
4                Системный аналитик                  432
5                          Аналитик                  404
6               Инженер-программист                  389
7                    Программист 1C                  360
8              Frontend-разработчик                  242
9     Инженер технической поддержки                  230

<strong> Для анализа небходимых навыков для получения наивысшей зарплаты предлагаю взглянуть на топ-20 вакансий 
</strong>

In [51]:
query_7_2 = f'''select distinct v.name "Название вакансии", max(salary_to) as "Максимальная з\п", v.key_skills "Необходимые навыки", e.name "Название компании"
from public.vacancies v
join public.employers e on e.id = v.employer_id
where v.salary_to is not null
group by v.name, v.key_skills, e.name
order by 2 desc
limit 20
'''

In [52]:
df_7_2 = pd.read_sql_query(query_7_2, connection)
display('Топ-20 самых высокооплачиваемых вакансий')
df_7_2

C:\Users\15arh\AppData\Local\Temp\ipykernel_5100\293923303.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_7_2 = pd.read_sql_query(query_7_2, connection)

'Топ-20 самых высокооплачиваемых вакансий'

,Название вакансии,Максимальная з\п,Необходимые навыки,Название компании
0,СТО/Директор по разработке,1000000,Laravel\tУправление проектами\tPHP\tVue.js\tPo...,Шеф Маркет
1,Брокер по продаже апартаментов,1000000,Ведение переговоров\tТелефонные переговоры\tРа...,Агентство недвижимости ЛЕТО
2,QA Automation Engineer,1000000,Тестирование\tHTML\tJavaScript\tGit\tТестирова...,iBEC Systems
3,1С:Эксперт по производительности 1С,950000,PostgreSQL\tMS SQL Server\t1С программирование,ЦТП
4,Senior Software Developer (upwork / иностранны...,935176,Английский язык\tДеловое общение\tУдаленная ра...,RuWork
5,Senior DevOps in Blockchain Startup,860000,AWS\tGCP\tDevOps\tGo\tGolang\tPython\tDocker\t...,Петухова Алия
6,FullStack Developer in Unicorn Company,860000,Java\tReact\tKotlin\tSpring Boot\tAWS\tGCP\tMo...,Петухова Алия
7,Frontend Developer in Unicorn Company,860000,Node.js\tJavaScript\tMongoDB\tAngular\tSpring ...,Петухова Алия
8,Product manager LATOKEN,800000,Product Management\tBusiness Development\tTeam...,LATOKEN
9,Java Backend Developer (remote),700000,Java\tSpring\tBackend\tQuarkus,LATOKEN
10,ML Engineer \ Data scientist,700000,Нейронные сети\tУдаленная работа\tMachine Lear...,Итон
11,Руководитель Отдела тестирования/QA,600000,Управление проектами\tAtlassian Jira\tTest cas...,ProfiStaff
12,"Программист-разработчик C#, SQL",600000,C#\tASP.NET\tWPF\t.NET Framework\tJavaScript\t...,ШтафунСофт
13,"Директор IT (HoReCa, Retail)",600000,Управление проектами\tСтратегическое мышление\...,BeRecruited
14,Chief Product Officer (CPO),600000,Управление продуктом\tCPO\tChief Product Offic...,Пикабу
15,Руководитель команды разработки,600000,Управление проектами\tОрганизаторские навыки\t...,Wanted
16,Liquidity Bots Developer,584485,"C#\t.NET Framework\tAMQP Rabbit / Kafka, MSA, ...",LATOKEN
17,"Senior Java Engineer (JavaSE, algorithms, opti...",584485,Статистический анализ\tАнглийский язык\tJava S...,BrainShells
18,C++ developer (to Berlin),557232,C/C++\tАнглийский язык,think-cell
19,C++ developer to Berlin,557232,C/C++\tАнглийский язык,think-cell

In [ ]:
connection.close()